version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: fleet_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: fleet_backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/fleetlink
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: fleet_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
